# Generated by Django 5.1.6 on 2025-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_services_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.TextField(),
        ),
    ]
